
if @POSITION = 'SH'
begin 
	UPDATE TB_R_PO_HEADER SET 
		  APPROVAL_STATUS = @APPROVAL_STATUS
		  ,APP_SH_BY = @NOREG_LOGIN
		  ,APP_SH_DT = GETDATE()
		  ,APP_SH_STATUS = @APPROVAL_STATUS

		  ,UPDATED_DT = GETDATE()
		  ,UPDATED_BY = @NOREG_LOGIN
	 WHERE PO_NUMBER = @PO_NUMBER
			and VEND_CODE = @VEND_CODE
END      
    
if @POSITION = 'DPH'
begin   
	UPDATE TB_R_PO_HEADER SET 
		  APPROVAL_STATUS = @APPROVAL_STATUS
		  ,APP_SH_BY = COALESCE(APP_SH_BY, @NOREG_LOGIN)
		  ,APP_SH_DT = COALESCE(APP_SH_DT, GETDATE())
		  ,APP_SH_STATUS = COALESCE(APP_SH_STATUS, @APPROVAL_STATUS)
		  
		  ,APP_DPH_BY = @NOREG_LOGIN
		  ,APP_DPH_DT = GETDATE()
		  ,APP_DPH_STATUS = @APPROVAL_STATUS

		  ,UPDATED_DT = GETDATE()
		  ,UPDATED_BY = @NOREG_LOGIN
	 WHERE PO_NUMBER = @PO_NUMBER
			and VEND_CODE = @VEND_CODE
end

if @POSITION = 'DH'
begin   
	UPDATE TB_R_PO_HEADER SET 
		  APPROVAL_STATUS = @APPROVAL_STATUS
		  ,APP_SH_BY = COALESCE(APP_SH_BY, @NOREG_LOGIN)
		  ,APP_SH_DT = COALESCE(APP_SH_DT, GETDATE())
		  ,APP_SH_STATUS = COALESCE(APP_SH_STATUS, @APPROVAL_STATUS)
		  
		  ,APP_DPH_BY = COALESCE(APP_SH_BY, @NOREG_LOGIN)
		  ,APP_DPH_DT = COALESCE(APP_SH_DT, GETDATE())
		  ,APP_DPH_STATUS = COALESCE(APP_SH_STATUS, @APPROVAL_STATUS)

		  ,APP_DH_BY = @NOREG_LOGIN
		  ,APP_DH_DT = GETDATE()
		  ,APP_DH_STATUS = @APPROVAL_STATUS

		  ,UPDATED_DT = GETDATE()
		  ,UPDATED_BY = @NOREG_LOGIN
	  WHERE PO_NUMBER = @PO_NUMBER
			and VEND_CODE = @VEND_CODE    
end