UPDATE 
	TB_R_GR_IR_FROM_SAP
SET 
	GR_STATUS = 'APPROVED'
	, UPDATED_DT = getdate()
	, UPDATED_BY = @UPDATED_BY
WHERE 
	1 = 1
	and PO_NUMBER =  @PO_NUMBER
	and PO_ITEM =  @PO_ITEM 
	and CAST(PO_DATE as DATE) >= CAST(CONVERT(datetime, @PO_DATE , 104) as DATE)
	and VEND_CODE = @VEND_CODE
	and GR_STATUS = @GR_STATUS
	and COALESCE(INVOICE_ID, '') = @INVOICE_ID

