SELECT 
		MAINTENANCE_APPROVAL_ID
		,ma.SUPPLIER_CD
		,ma.APPROVER_UNIT_CD
		,s.SUPPLIER_NAME
		,emp.NAME as APPROVER_NAME
FROM TB_M_MAINTENANCE_APPROVAL ma
	LEFT JOIN TB_M_SUPPLIER s on s.SUPPLIER_CD = ma.SUPPLIER_CD
	left join VW_EMPLOYEE_PROFILE emp on emp.UNIT_CODE = ma.APPROVER_UNIT_CD and emp.POSITION = 'Section Head'

WHERE 1 = 1
	and MAINTENANCE_APPROVAL_ID = @MAINTENANCE_APPROVAL_ID	