SELECT 
		sum(MATDOC_AMOUNT) AS PO_TOTAL_AMOUNT		
		, PO_NUMBER
		, PO_ITEM
		, gr.VEND_CODE
		, CALCULATE_TAX
		, inv.INVOICE_ID
		, STAMP_AMOUNT	
		, inv.TAX_INVOICE_AMOUNT	
	FROM TB_R_GR_IR_FROM_SAP gr
		left join TB_M_SUPPLIER s on s.SUPPLIER_CD = gr.VEND_CODE
		left join TB_R_INVOICE inv on inv.INVOICE_ID = gr.INVOICE_ID
	where 1=1
		and inv.INVOICE_ID = @INVOICE_ID

	group by 
	PO_NUMBER, PO_ITEM, gr.VEND_CODE,
	inv.INVOICE_ID ,calculate_TAX, STAMP_AMOUNT, inv.TAX_INVOICE_AMOUNT