DECLARE @@sqlstate VARCHAR(MAX);
DECLARE @@GR_SA_NO VARCHAR(MAX);
DECLARE @@GR_SA_ITEM_NO VARCHAR(MAX);
DECLARE @@USER_ID VARCHAR(MAX);
DECLARE @@LINK_SERVER_NM VARCHAR(MAX);
DECLARE @@LINK_DB_NM VARCHAR(MAX);
DECLARE @@RESULT VARCHAR(MAX);

SET @@sqlstate = '';
SET @@GR_SA_NO = @GR_SA_NO;
SET @@GR_SA_ITEM_NO = @GR_SA_ITEM_NO;
SET @@USER_ID = @USER_ID;
SET @@LINK_SERVER_NM = (SELECT SYSTEM_VALUE_TEXT FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'LINKED_SERVER_NAME' AND SYSTEM_TYPE = 'PAS')
SET @@LINK_DB_NM = (SELECT SYSTEM_VALUE_TEXT FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'LINKED_DB_NAME' AND SYSTEM_TYPE = 'PAS')

SET @@sqlstate = '
IF EXISTS (
		SELECT GR_SA_STATUS
		FROM [' + @@LINK_SERVER_NM + '].[' + @@LINK_DB_NM + '].[dbo].[TB_R_GR_SA_ITEM]
		WHERE 1 = 1
			AND GR_SA_NO = ' + @@GR_SA_NO + '
			AND GR_SA_ITEM_NO = ' + @@GR_SA_ITEM_NO + '
			AND ''' + @@USER_ID + ''' = ''PAS''
		)
BEGIN
	IF EXISTS (
			SELECT GR_SA_STATUS
			FROM [' + @@LINK_SERVER_NM + '].[' + @@LINK_DB_NM + '].[dbo].[TB_R_GR_SA_ITEM]
			WHERE 1 = 1
				AND GR_SA_NO = ' + @@GR_SA_NO + '
				AND GR_SA_ITEM_NO = ' + @@GR_SA_ITEM_NO + '
				AND ''' + @@USER_ID + ''' = ''PAS''
				AND GR_SA_STATUS = ''65''
			)
	BEGIN
		SELECT ''Y''
	END
	ELSE
	BEGIN
		SELECT ''N''
	END
END
ELSE
BEGIN
	SELECT ''Y''
END'

EXECUTE(@@sqlstate);