update 
	TB_R_INVOICE
set 
	[STATUS] = 'CANCELLED',
	GR_CANCEL = NULL,
	REVERSE_REASON = @REASON_IN,
	REVERSE_POST_DT = @POST_DATE_IN,
	REVERSE_SAP_DOC_NO = @REV_INV_NO_OUT ,
	REVERSE_SAP_YEAR = @REV_YEAR_OUT,
	UPDATED_BY = @UPDATED_BY,
	UPDATED_DT = getdate()
where 
	1=1
and INVOICE_ID = @INVOICE_ID


update 
	TB_R_GR_IR_FROM_SAP
set 
	GR_STATUS = 'APPROVED'
	,INVOICE_ID = NULL
	,UPDATED_BY = @UPDATED_BY
	,UPDATED_DT = getdate()
where 
	1=1
and 
	INVOICE_ID = @INVOICE_ID


/*update 
	TB_R_VAT_IN_H
set 
	IS_USED = '0'
	,CHANGED_BY = @UPDATED_BY
	,CHANGED_DT = getdate()
where 
	1=1
and 
	TAX_INVOICE_NO = @TAX_INVOICE_NO
*/


DECLARE @sql NVARCHAR(MAX);
		
SET @sql = '
			UPDATE
				OPENQUERY([10.16.25.2], ''
				select V1.USED AS USED, V1.CHANGED_BY, V1.CHANGED_DT from TMMIN_E_FAKTUR_UAT.dbo.tb_r_vat_in_h v1 
				where v1.tax_invoice_no = '''''+@TAX_INVOICE_NO+'''''
					and v1.REPLACEMENT_FG = (SELECT MAX(v2.REPLACEMENT_FG) FROM TMMIN_E_FAKTUR_UAT.dbo.TB_R_VAT_IN_H V2 
					WHERE V2.TAX_INVOICE_NO = v1.TAX_INVOICE_NO)'')
				SET USED = ''N'',
					CHANGED_BY = '''+@UPDATED_BY+''',
					CHANGED_DT = GETDATE()'

exec sp_executesql @sql