IF OBJECT_ID(N'tempdb..#TEMP_INVOICE_SAP_INPUT') IS NOT NULL
	DROP TABLE #TEMP_INVOICE_SAP_INPUT

IF OBJECT_ID(N'tempdb..#TEMP_INVOICE_SAP_GR_DATA') IS NOT NULL
	DROP TABLE #TEMP_INVOICE_SAP_GR_DATA

IF OBJECT_ID(N'tempdb..#TEMP_GR_IR_FROM_SAP') IS NOT NULL
	DROP TABLE #TEMP_GR_IR_FROM_SAP

SELECT DISTINCT INVOICE_ID
	,ON_PROCESS
	,SAP_STATUS
	,INV_DATE
	,TAX_CODE
	,TERM_PAY
	,POST_DATE
	,ISNULL(ITEM_TEXT, '') ITEM_TEXT
	,PAY_METHOD
	,BASE_DATE
INTO #TEMP_INVOICE_SAP_INPUT
FROM TB_R_INVOICE_SAP_INPUT
WHERE SAP_STATUS IS NULL
	AND ON_PROCESS = 'Y'

SELECT DISTINCT A.INVOICE_ID
	,A.PO_NUMBER
	,A.GR_NUMBER
	,A.GR_ITEM
	,A.ON_PROCESS
INTO #TEMP_INVOICE_SAP_GR_DATA
FROM TB_R_INVOICE_SAP_GR_DATA A
JOIN #TEMP_INVOICE_SAP_INPUT B ON A.INVOICE_ID = B.INVOICE_ID
WHERE A.ON_PROCESS = 'Y'

SELECT DISTINCT A.INVOICE_ID
	,A.MATDOC_NUMBER
	,A.MATDOC_DATE
	,A.MATDOC_ITEM
	,A.MATDOC_AMOUNT
	,A.TRANS_TYPE
	,A.GR_TYPE
	,A.WBS_NO
	,ISNULL(A.COST_CENTER, '') COST_CENTER
INTO #TEMP_GR_IR_FROM_SAP
FROM TB_R_GR_IR_FROM_SAP A
JOIN #TEMP_INVOICE_SAP_INPUT B ON A.INVOICE_ID = B.INVOICE_ID

DELETE
FROM TB_T_BH00021

INSERT INTO TB_T_BH00021 (
	RECORD_ID
	,COUNTRY_CD
	,COMPANY_CD
	,COMPANY_BRANCH
	,LEGACY_SYSTEM
	,PART_CATEGORY
	,DOC_NO
	,DOC_TYPE
	,DOC_DT
	,DOC_CURR
	,TAX_CD
	,WITHHOLDING_TAX_CD
	,TERM_OF_PAYMENT
	,DUE_DT
	,REFF_DOC_NO
	,ORACLE_SUPP_CD
	,SUPP_CD
	,ORACLE_SUPP_PLANT_CD
	,SUPP_PLANT_CD
	,REFF_CUSTOMER_INV_NO
	,ORACLE_CUST_CD
	,CUST_CD
	,ORACLE_CUST_PLANT_CD
	,CUST_PLANT_CD
	,PART_RECEIVED_DT
	,PO_NO
	,VEHICLE_CATEGORY
	,MODEL_CD
	,FIXED_ASSET_NO
	,ITEM_CD
	,ITEM_QTY
	,UOM
	,STD_UNIT_COST
	,STD_COST_AMT
	,STD_TTL_AMT
	,ACT_UNIT_COST
	,ACT_COST_AMT
	,ACT_TTL_AMT
	,VARIANCE_AMT
	,TAX_AMT
	,GRAND_AMT
	,WITHHOLDING_TAX_BASE_AMT
	,WITHHOLDING_TAX_AMT
	,ORDER_TYPE
	,REASON_CD
	,COST_CENTER
	,BUDGET_NO
	,DESCRIPTION
	,MARK_CD
	,SIGN_CD
	,STOCK_MOVEMENT_FLAG
	,CANCEL_FLAG
	,INTERFACE_TYPE_FLAG
	,COA_FLAG
	,COA_SEGMENT_1
	,COA_SEGMENT_2
	,COA_SEGMENT_3
	,COA_SEGMENT_4
	,COA_SEGMENT_5
	,COA_SEGMENT_6
	,COA_SEGMENT_7
	,COA_SEGMENT_8
	,COA_SEGMENT_9
	,COA_SEGMENT_10
	,HEADER_RESERVED_1
	,HEADER_RESERVED_2
	,HEADER_RESERVED_3
	,HEADER_RESERVED_4
	,DETAIL_RESERVED_1
	,DETAIL_RESERVED_2
	,DETAIL_RESERVED_3
	,DETAIL_RESERVED_4
	,DETAIL_RESERVED_5
	,DETAIL_RESERVED_6
	,GR_NUMBER
	,MATERIAL_INDICATOR
	,INVOICE_ID
	,CREATED_BY
	,CREATED_DT
	,PAY_METHOD
	)
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), (
				ROW_NUMBER() OVER (
					ORDER BY TB.DETAIL_RESERVED_4
						,TB.GR_NUMBER
						,TB.GR_ITEM
					)
				)), 7) RECORD_ID
	,COUNTRY_CD
	,COMPANY_CD
	,COMPANY_BRANCH
	,LEGACY_SYSTEM
	,PART_CATEGORY
	,DOC_NO
	,DOC_TYPE
	,DOC_DT
	,DOC_CURR
	,TAX_CD
	,WITHHOLDING_TAX_CD
	,TERM_OF_PAYMENT
	,DUE_DT
	,REFF_DOC_NO
	,ORACLE_SUPP_CD
	,SUPP_CD
	,ORACLE_SUPP_PLANT_CD
	,SUPP_PLANT_CD
	,REFF_CUSTOMER_INV_NO
	,ORACLE_CUST_CD
	,CUST_CD
	,ORACLE_CUST_PLANT_CD
	,CUST_PLANT_CD
	,PART_RECEIVED_DT
	,PO_NO
	,VEHICLE_CATEGORY
	,MODEL_CD
	,FIXED_ASSET_NO
	,ITEM_CD
	,ITEM_QTY
	,UOM
	,STD_UNIT_COST
	,STD_COST_AMT
	,STD_TTL_AMT
	,ACT_UNIT_COST
	,ACT_COST_AMT
	,ACT_TTL_AMT
	,VARIANCE_AMT
	,TAX_AMT
	,GRAND_AMT
	,WITHHOLDING_TAX_BASE_AMT
	,WITHHOLDING_TAX_AMT
	,ORDER_TYPE
	,REASON_CD
	,COST_CENTER
	,BUDGET_NO
	,DESCRIPTION
	,MARK_CD
	,SIGN_CD
	,STOCK_MOVEMENT_FLAG
	,CANCEL_FLAG
	,INTERFACE_TYPE_FLAG
	,COA_FLAG
	,COA_SEGMENT_1
	,COA_SEGMENT_2
	,COA_SEGMENT_3
	,COA_SEGMENT_4
	,COA_SEGMENT_5
	,COA_SEGMENT_6
	,COA_SEGMENT_7
	,COA_SEGMENT_8
	,COA_SEGMENT_9
	,COA_SEGMENT_10
	,HEADER_RESERVED_1
	,HEADER_RESERVED_2
	,HEADER_RESERVED_3
	,HEADER_RESERVED_4
	,DETAIL_RESERVED_1
	,DETAIL_RESERVED_2
	,DETAIL_RESERVED_3
	,DETAIL_RESERVED_4
	,DETAIL_RESERVED_5
	,DETAIL_RESERVED_6
	,GR_NUMBER
	,MATERIAL_INDICATOR
	,INVOICE_ID
	,CREATED_BY
	,CREATED_DT
	,PAY_METHOD
FROM (
	SELECT DISTINCT D.GR_ITEM
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'COUNTRY_CD'
			) COUNTRY_CD
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'COMPANY_CD'
			) COMPANY_CD
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'COMPANY_BRANCH'
			) COMPANY_BRANCH
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'LEGACY'
			) LEGACY_SYSTEM
		,(
			CASE 
				WHEN UPPER(E.TRANS_TYPE) = 'DIRECT'
					THEN 'M'
				ELSE 'N'
				END
			) PART_CATEGORY
		,(
			CASE 
				WHEN ISNULL(A.TAX_INVOICE_NO, '') = ''
					THEN A.INVOICE_NO
				ELSE A.TAX_INVOICE_NO
				END
			) DOC_NO
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'DOC_TYPE'
			) DOC_TYPE
		,CONVERT(VARCHAR, B.INV_DATE, 112) DOC_DT
		,A.CURRENCY DOC_CURR
		,B.TAX_CODE TAX_CD
		,ISNULL(A.WITHOLDING_TAX_CD, '') WITHHOLDING_TAX_CD
		,B.TERM_PAY TERM_OF_PAYMENT
		--,CONVERT(VARCHAR, B.INV_DATE, 112) DUE_DT
		,CONVERT(VARCHAR, B.BASE_DATE, 112) DUE_DT
		,'' REFF_DOC_NO
		,'' ORACLE_SUPP_CD
		,A.SUPPLIER_CD SUPP_CD
		,'' ORACLE_SUPP_PLANT_CD
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'SUPPLIER_CD'
			) SUPP_PLANT_CD
		,'' REFF_CUSTOMER_INV_NO
		,'' ORACLE_CUST_CD
		,'' CUST_CD
		,'' ORACLE_CUST_PLANT_CD
		,'' CUST_PLANT_CD
		,CONVERT(VARCHAR, B.POST_DATE, 112) PART_RECEIVED_DT
		,D.PO_NUMBER PO_NO
		,'' VEHICLE_CATEGORY
		,'' MODEL_CD
		,'' FIXED_ASSET_NO
		,'' ITEM_CD
		,'0000000.00' ITEM_QTY
		,'' UOM
		,'00000000000.00' STD_UNIT_COST
		,'00000000000.00' STD_COST_AMT
		,'00000000000.00' STD_TTL_AMT
		,'00000000000.00' ACT_UNIT_COST
		,'00000000000.00' ACT_COST_AMT
		,RIGHT('000000000000000000' + CONVERT(VARCHAR(21), E.MATDOC_AMOUNT), 21) ACT_TTL_AMT
		,'00000000000.00' VARIANCE_AMT
		,RIGHT('000000000000000000' + CONVERT(VARCHAR(21), ABS(A.TAX_INVOICE_AMOUNT)), 21) TAX_AMT
		,RIGHT('000000000000000000' + CONVERT(VARCHAR(21), ABS(A.TOTAL_AMOUNT)), 21) GRAND_AMT
		,RIGHT('000000000000000000' + CONVERT(VARCHAR(21), ABS(A.TAX_BASE)), 21) WITHHOLDING_TAX_BASE_AMT
		,ISNULL((
				SELECT TOP 1 RIGHT('000000000000000000' + CONVERT(VARCHAR(21), AG.AMOUNT), 21)
				FROM TB_R_INVOICE_SAP_GL AG
				WHERE AG.GL_ACCOUNT = (
						SELECT TOP 1 SYSTEM_VALUE_TEXT
						FROM TB_M_SYSTEM
						WHERE SYSTEM_TYPE = 'BH00021'
							AND SYSTEM_CD = 'GL_ZPB3'
						)
					AND AG.INVOICE_ID = A.INVOICE_ID
				), '') WITHHOLDING_TAX_AMT
		,'' ORDER_TYPE
		,'' REASON_CD
		,E.COST_CENTER COST_CENTER
		,'' BUDGET_NO
		,'' DESCRIPTION
		,'N' MARK_CD
		,'+' SIGN_CD
		,'N' STOCK_MOVEMENT_FLAG
		,'N' CANCEL_FLAG
		,'O' INTERFACE_TYPE_FLAG
		,'L' COA_FLAG
		,'' COA_SEGMENT_1
		,'' COA_SEGMENT_2
		,'' COA_SEGMENT_3
		,'' COA_SEGMENT_4
		,'' COA_SEGMENT_5
		,'' COA_SEGMENT_6
		,'' COA_SEGMENT_7
		,'' COA_SEGMENT_8
		,'' COA_SEGMENT_9
		,'' COA_SEGMENT_10
		,'' HEADER_RESERVED_1
		,(
			CASE 
				WHEN UPPER(E.TRANS_TYPE) = 'DIRECT'
					THEN '1'
				ELSE '2'
				END
			) HEADER_RESERVED_2
		,CONVERT(VARCHAR, B.POST_DATE, 112) HEADER_RESERVED_3
		,(
			SELECT TOP 1 SYSTEM_VALUE_TEXT
			FROM TB_M_SYSTEM
			WHERE SYSTEM_TYPE = 'BH00021'
				AND SYSTEM_CD = 'SUPP_BRANCH'
			) HEADER_RESERVED_4
		,(
			CASE 
				WHEN LEN(D.GR_NUMBER) > 10
					THEN REPLACE(D.GR_NUMBER, LEFT(D.GR_NUMBER, 10), '')
				ELSE ''
				END
			) DETAIL_RESERVED_1
		,ISNULL((
				SELECT TOP 1 RIGHT('00000000000000000' + CONVERT(VARCHAR(20), GG.AMOUNT), 20)
				FROM TB_R_INVOICE_SAP_GL GG
				WHERE GG.GL_ACCOUNT = (
						SELECT TOP 1 SYSTEM_VALUE_TEXT
						FROM TB_M_SYSTEM
						WHERE SYSTEM_TYPE = 'BH00021'
							AND SYSTEM_CD = 'GL_STAMP'
						)
					AND GG.INVOICE_ID = A.INVOICE_ID
				), '') DETAIL_RESERVED_2
		,(
			CASE 
				WHEN A.CURRENCY = 'IDR'
					THEN (
							SELECT TOP 1 SYSTEM_VALUE_TEXT
							FROM TB_M_SYSTEM
							WHERE SYSTEM_TYPE = 'BH00021'
								AND SYSTEM_CD = 'GL_OTH_DOM'
							)
				ELSE (
						SELECT TOP 1 SYSTEM_VALUE_TEXT
						FROM TB_M_SYSTEM
						WHERE SYSTEM_TYPE = 'BH00021'
							AND SYSTEM_CD = 'GL_OTH_IMPORT'
						)
				END
			) DETAIL_RESERVED_3
		,A.INVOICE_NO DETAIL_RESERVED_4
		,ISNULL(E.WBS_NO, '') DETAIL_RESERVED_5
		,B.ITEM_TEXT DETAIL_RESERVED_6
		,LEFT(D.GR_NUMBER, 10) GR_NUMBER
		,(
			CASE 
				WHEN UPPER(E.TRANS_TYPE) = 'DIRECT'
					AND UPPER(E.GR_TYPE) = 'INV'
					THEN 'A'
				WHEN UPPER(E.TRANS_TYPE) = 'INDIRECT'
					AND UPPER(E.GR_TYPE) = 'INV'
					THEN 'B'
				WHEN UPPER(E.TRANS_TYPE) = 'INDIRECT'
					AND UPPER(E.GR_TYPE) = 'ASS'
					THEN 'C'
				WHEN UPPER(E.TRANS_TYPE) = 'INDIRECT'
					AND UPPER(E.GR_TYPE) = 'EXP'
					THEN 'D'
				END
			) MATERIAL_INDICATOR
		,A.INVOICE_ID INVOICE_ID
		,'SYSTEM' CREATED_BY
		,GETDATE() CREATED_DT
		,B.PAY_METHOD
	FROM TB_R_INVOICE A
	JOIN #TEMP_INVOICE_SAP_INPUT B ON A.INVOICE_ID = B.INVOICE_ID
	JOIN #TEMP_INVOICE_SAP_GR_DATA D ON A.INVOICE_ID = D.INVOICE_ID
	JOIN #TEMP_GR_IR_FROM_SAP E ON A.INVOICE_ID = E.INVOICE_ID
		AND D.GR_NUMBER = E.MATDOC_NUMBER
		AND D.GR_ITEM = E.MATDOC_ITEM
	WHERE A.ON_PROCESS_SAP_POST = 'Y'
		AND B.ON_PROCESS = 'Y'
		AND D.ON_PROCESS = 'Y'
		AND B.SAP_STATUS IS NULL
	) TB
