UPDATE 
	TB_R_GR_IR_FROM_SAP
SET 
	GR_STATUS = 'APPROVED'
	, UPDATED_DT = getdate()
	, UPDATED_BY = @UPDATED_BY
	, APPROVED_DT = getdate()
	, APPROVED_BY = @APPROVED_BY
WHERE 
	1 = 1
	and GR_IR_ID = @GR_IR_ID

