DECLARE @@APPROVED VARCHAR(20) = ''
IF EXISTS(SELECT 0 FROM TB_R_GR_IR_FROM_SAP 
WHERE PO_NUMBER = @PO_NUMBER 
		AND PO_ITEM = @PO_ITEM 
		AND MATDOC_NUMBER = @MATDOC_NUMBER
		AND MATDOC_ITEM = @MATDOC_ITEM 
		AND GR_STATUS = 'APPROVED')
BEGIN
	SET @@APPROVED = 'APPROVED'
END
ELSE
BEGIN
	SET @@APPROVED = 'NOT APPROVED'
END

SELECT @@APPROVED