DECLARE @@LINKED_SERVER VARCHAR(100)
,@@CATALOG_DB VARCHAR(100)
,@@QUERY VARCHAR (MAX)

SELECT TOP 1 @@LINKED_SERVER = SYSTEM_VALUE_TEXT
		FROM TB_M_SYSTEM
		WHERE SYSTEM_TYPE = 'LINKED_SERVER'
			AND SYSTEM_CD = 'INVOICE_PAS'

SELECT TOP 1 @@CATALOG_DB = SYSTEM_VALUE_TEXT
		FROM TB_M_SYSTEM
		WHERE SYSTEM_TYPE = 'CATALOG_DB'
			AND SYSTEM_CD = 'INVOICE_PAS'

SET @@QUERY = 'DELETE FROM [' + @@LINKED_SERVER + '].[' + @@CATALOG_DB + '].dbo.TB_R_INVOICE_INFO WHERE INVOICE_ID = ' + @INVOICE_ID + ' '

EXEC (@@QUERY);

