DECLARE @@sqlstate varchar(max);
DECLARE @@DOC_TITLE varchar(100)
		,@@STATUS VARCHAR(MAX)
		,@@RELEASE_DATE_FROM VARCHAR(50)
		,@@RELEASE_DATE_TO VARCHAR(50)
		,@@NUMBERFROM VARCHAR(max)
		,@@NUMBERTO VARCHAR(max)


SET @@sqlstate = '';
SET @@DOC_TITLE = @DOC_TITLE;
SET @@RELEASE_DATE_FROM = @RELEASE_DATE_FROM
SET @@RELEASE_DATE_TO = @RELEASE_DATE_TO;
SET @@STATUS = @STATUS
SET @@NUMBERFROM = @NUMBERFROM
SET @@NUMBERTO = @NUMBERTO


SET @@sqlstate = @@sqlstate + '
	SELECT * FROM 
	( 
	SELECT 
		ROW_NUMBER () OVER (ORDER BY DATE_RELEASE ASC) AS NUMBER
		,DOCUMENT_ID
	  ,ANNOUNCEMENT_TITLE
	  ,FILE_LOCATION
	  ,DATE_RELEASE
	  ,CONVERT(VARCHAR, DATE_RELEASE, 104) DATE_RELEASE_STR
	  ,STATUS
	  ,CREATED_BY
	  ,CREATED_DT
	  ,CONVERT(VARCHAR, CREATED_DT, 104) CREATED_DT_STR
	  ,CHANGED_BY
	  ,CHANGED_DT
	  ,CONVERT(VARCHAR, CHANGED_DT, 104) CHANGED_DT_STR
	  FROM TB_M_ANNOUNCEMENT
	WHERE 1=1
	  ';
	IF(@@DOC_TITLE <> '' AND @@DOC_TITLE is not null)
	BEGIN
		SET @@sqlstate = @@sqlstate + '
		AND ANNOUNCEMENT_TITLE IN ('+@@DOC_TITLE+') '
	END

	IF(@@RELEASE_DATE_FROM <> '')
	BEGIN
		SET @@sqlstate = @@sqlstate + '
		AND CAST(DATE_RELEASE AS DATE) >= CAST(CONVERT(DATETIME, ''' + @@RELEASE_DATE_FROM + ''' , 104) AS DATE)'
	END

	IF(@@RELEASE_DATE_TO <> '')
	BEGIN
		SET @@sqlstate = @@sqlstate + '
		AND CAST(DATE_RELEASE AS DATE) <= CAST(CONVERT(DATETIME, ''' + @@RELEASE_DATE_TO + ''' , 104) AS DATE)'
	END

	IF(@@STATUS <> '' AND @@STATUS is not null)
	BEGIN
		SET @@sqlstate = @@sqlstate + '
		AND STATUS IN ('+@@STATUS+') '
	END

SET @@sqlstate = @@sqlstate + '	
	) REFF
WHERE NUMBER BETWEEN ' + @@NUMBERFROM + '
		AND ' + @@NUMBERTO

execute(@@sqlstate)