SELECT DOCUMENT_ID
	  ,ANNOUNCEMENT_TITLE
	  ,RIGHT(FILE_LOCATION, CHARINDEX('/', REVERSE(FILE_LOCATION)) -1)  AS FILE_NAME
	  ,FILE_LOCATION
	  ,CONVERT(VARCHAR, DATE_RELEASE, 104) DATE_RELEASE_STR
	  ,STATUS
	  ,CREATED_BY
	  ,CREATED_DT
	  ,CONVERT(VARCHAR, CREATED_DT, 104) CREATED_DT_STR
	  ,CHANGED_BY
	  ,CHANGED_DT
	  ,CONVERT(VARCHAR, CHANGED_DT, 104) CHANGED_DT_STR
	  FROM TB_M_ANNOUNCEMENT
	WHERE 1=1
		AND DOCUMENT_ID = @DOCUMENT_ID