SELECT * FROM 
(
	SELECT 
	ROW_NUMBER () OVER (ORDER BY DATE_RELEASE ASC) AS NUMBER,
	DOCUMENT_ID,
	ANNOUNCEMENT_TITLE,
	FILE_LOCATION,
	DATE_RELEASE,
	[STATUS],
	CREATED_BY,
	CREATED_DT,
	CHANGED_BY,
	CHANGED_DT
	FROM TB_M_ANNOUNCEMENT
	WHERE [STATUS] = @STATUS
) 
REFF WHERE Number BETWEEN @NumberFrom AND @NumberTo
ORDER BY DATE_RELEASE ASC 