DECLARE @@val INT = 0

SELECT @@val = SYSTEM_VALUE_NUM FROM PROCUREMENT.dbo.TB_M_SYSTEM WHERE SYSTEM_CD = 'EFAKTUR_EXPIRED' and SYSTEM_TYPE = 'CREATE_INV'

SELECT * FROM 
(
	SELECT 
		ROW_NUMBER () OVER (ORDER BY h.TAX_INVOICE_NO) AS Number, * 
	FROM 
		TB_R_VAT_IN_H h
	WHERE
		h.SUPPLIER_CODE = @SUPPLIER_CD-- substring(@SUPPLIER_CD, patindex('%[^0]%',@SUPPLIER_CD), 10)
		AND 
		h.TAX_INVOICE_NO like '%' + ISNULL(@Parameter,'') + '%'
		
		AND ISNULL(USED, 'N') != 'Y'
		AND DATEADD(MONTH, @@val, TAX_INVOICE_DT) >= GETDATE()
) TB WHERE Number BETWEEN @NumberFrom AND @NumberTo
	