DECLARE @@EXIST VARCHAR(10) = ''
IF EXISTS(SELECT 0 FROM TB_R_GR_IR_FROM_SAP 
WHERE PO_NUMBER = @PO_NUMBER 
		AND PO_ITEM = @PO_ITEM 
		AND MATDOC_NUMBER = @MATDOC_NUMBER
		AND MATDOC_ITEM = @MATDOC_ITEM 
		AND GR_STATUS = 'APPROVED' 
		AND INVOICE_ID IS NOT NULL)
BEGIN
	SET @@EXIST = 'EXIST'
END
ELSE
BEGIN
	SET @@EXIST = 'NOT EXIST'
END

SELECT @@EXIST