DECLARE @@sqlstate varchar(8000);
DECLARE @@INVOICE_NO varchar(100);
DECLARE @@INVOICE_ID  varchar(8000);
DECLARE @@LinkedServerPas  varchar(8000);


--update
DECLARE @@LinkedServer nvarchar(4000);
SET @@LinkedServer = '[' + @LinkedServer + ']';

SET @@sqlstate = '';
SET @@INVOICE_NO = @INVOICE_NO;	
SET @@INVOICE_ID = @INVOICE_ID;



SET @@sqlstate = '
	SELECT 
	NTABLE.*,EFAKTUR.TAX_INVOICE_DT_STR, EFAKTUR.TAX_AMOUNT 
	FROM (
	SELECT DISTINCT TOP 1
	GR.PO_CATEGORY,
	INV.INVOICE_NO,
	INV.INVOICE_ID,
	INV.STATUS,
	INV.INVOICE_DATE,
	CONVERT(VARCHAR(30), INV.INVOICE_DATE , 104) as INVOICE_DATE_STR,
	INV.TURN_OVER,
	INV.TAX_BASE,
	INV.CALCULATE_TAX,
	INV.WITHOLDING_TAX_CD,
	INV.SUPPLIER_CD,
	INV.CHECKBOX_STAMP,
	INV.TOTAL_AMOUNT,
	INV.TAX_INVOICE_AMOUNT,
	INV.TAX_INVOICE_NO,
	INV.NOTICE_FLAG,
	INV.CERTIFICATE_ID,
	DD.DD_STATUS,AN.AGREEMENT_NO,
	CONVERT(VARCHAR(30), AN.EXP_DATE, 104) as EXP_DATE,
	(SELECT COUNT(1) FROM TB_R_GR_IR_FROM_SAP WHERE INVOICE_ID = '''+@@INVOICE_ID+''') as TOTAL_GR_ITEM --(SELECT COUNT(1) FROM TB_R_GR_IR_FROM_SAP WHERE INVOICE_ID = INV.INVOICE_ID) as TOTAL_GR_ITEM --edit riani(20220726) --> ganti INV.INVOICE_ID jadi @@INVOICE_ID
	
	FROM TB_R_INVOICE INV JOIN TB_R_GR_IR_FROM_SAP GR ON GR.INVOICE_ID = INV.INVOICE_ID 
	LEFT JOIN TB_M_DUE_DILLIGENCE DD ON DD.SAP_VENDOR_ID = INV.SUPPLIER_CD
	LEFT JOIN TB_M_AGREEMENT_NO AN ON AN.VENDOR_CODE = DD.VENDOR_CODE
		LEFT JOIN (SELECT MAX(EXP_DATE) As MAXDATE,VENDOR_CODE FROM TB_M_AGREEMENT_NO GROUP BY VENDOR_CODE) G
			ON AN.VENDOR_CODE = G.VENDOR_CODE AND AN.EXP_DATE = G.MAXDATE
	WHERE 
	INV.INVOICE_NO = '''+@@INVOICE_NO+'''  
	AND INV.INVOICE_ID = '''+@@INVOICE_ID+''' ) NTABLE
	LEFT JOIN (
	SELECT 
	INVOICE_NO,
	TAX_INVOICE_DT_STR,
	TAX_AMOUNT,
	TAX_INVOICE_NO
	FROM OPENQUERY('+ @@LinkedServer + ', 
	''SELECT INVOICE_NO AS INVOICE_NO,
		CONVERT(VARCHAR(30), VAT.TAX_INVOICE_DT , 104) AS TAX_INVOICE_DT_STR,VAT.TAX_INVOICE_NO,VAT.VAT_PRICE AS TAX_AMOUNT
		FROM TMMIN_E_FAKTUR_SAPHANA.dbo.TB_R_VAT_IN_H VAT 
	'')) EFAKTUR 
	ON NTABLE.TAX_INVOICE_NO  = EFAKTUR.TAX_INVOICE_NO 
';

--PRINT @@sqlstate

execute(@@sqlstate);

