DECLARE @@sqlstate varchar(max);
DECLARE @@INVOICE_ID varchar(100);
DECLARE @@CERTIFICATE_ID varchar(100);
DECLARE @@SUPPLIER_CD varchar(100);

--update
DECLARE @@LinkedServer nvarchar(4000);
SET @@LinkedServer = '[' + @LinkedServer + ']';
--SET @@LinkedServer = '[52.77.208.248]';
--SET @@LinkedServer = '[10.16.25.2]';

SET @@sqlstate = '';
SET @@INVOICE_ID = @INVOICE_ID;
SET @@CERTIFICATE_ID = @CERTIFICATE_ID;
SET @@SUPPLIER_CD = @SUPPLIER_CD;

SET @@sqlstate = @@sqlstate + '
	SELECT NTABLE.*, EFAKTUR.TAX_INVOICE_DT FROM (
	SELECT 
		ROW_NUMBER () OVER (ORDER BY INVOICE_DATE asc) AS Number
		,INVOICE_ID
		,inv.INVOICE_NO
		,INVOICE_DATE
		,inv.TAX_INVOICE_NO
		,CURRENCY
		,TURN_OVER
		,TAX_BASE
		,CALCULATE_TAX
		,CHECKBOX_STAMP
		,FLOOR(TOTAL_AMOUNT) TOTAL_AMOUNT
		,inv.[STATUS]
		,PAYMENT_PLAN_DATE
		,PAYMENT_ACTUAL_DATE
		,NOTICE_BY
		,NOTICE_REMARK
		,NOTICE_DATE
		,CERTIFICATE_ID
		,SUBMIT_DT
		,SUBMIT_BY
		,RECEIVED_STATUS
		,RECEIVED_DT
		,FLOOR(TAX_INVOICE_AMOUNT) TAX_INVOICE_AMOUNT
		,inv.[SAP_DOC_NO]
		,SAP_YEAR
		,REVERSE_REASON
		,REVERSE_POST_DT
		,SUPPLIER_NAME
		,inv.SUPPLIER_CD
	FROM TB_R_INVOICE inv
		left join TB_M_SUPPLIER s on s.SUPPLIER_CD = inv.SUPPLIER_CD

	where 1=1
		';

IF(@@INVOICE_ID <> '' AND @@INVOICE_ID is not null)
BEGIN
	SET @@sqlstate = @@sqlstate + '
	and INVOICE_ID = '''+ @@INVOICE_ID + ''' ';
END

IF(@@CERTIFICATE_ID <> '' AND @@CERTIFICATE_ID is not null)
BEGIN
	SET @@sqlstate = @@sqlstate + '
	and CERTIFICATE_ID = '''+ @@CERTIFICATE_ID + ''' ';
END

IF(@@SUPPLIER_CD <> '' AND @@SUPPLIER_CD is not null)
BEGIN
	SET @@sqlstate = @@sqlstate + '
	and inv.SUPPLIER_CD = '''+ @@SUPPLIER_CD + ''' ';
END


SET @@sqlstate = @@sqlstate + ' ) NTABLE
	LEFT JOIN (
		SELECT TAX_INVOICE_NO, TAX_INVOICE_DT FROM OPENQUERY('+ @@LinkedServer + ', 
		''
			select  v1.TAX_INVOICE_NO AS TAX_INVOICE_NO, V1.TAX_INVOICE_DT AS TAX_INVOICE_DT from TMMIN_E_FAKTUR_UAT.dbo.tb_r_vat_in_h v1 
			WHERE 
			v1.REPLACEMENT_FG = (SELECT MAX(v2.REPLACEMENT_FG) FROM TMMIN_E_FAKTUR_UAT.dbo.TB_R_VAT_IN_H V2 
			WHERE V2.TAX_INVOICE_NO = v1.TAX_INVOICE_NO)'')
		
	) EFAKTUR

	ON NTABLE.TAX_INVOICE_NO = EFAKTUR.TAX_INVOICE_NO
'
--select @@sqlstate
execute(@@sqlstate);