DECLARE @@sqlstate varchar(max);
DECLARE @@INVOICE_NO varchar(100);
DECLARE @@INVOICE_ID  varchar(MAX);

--update
DECLARE @@LinkedServer nvarchar(4000);
SET @@LinkedServer = '[' + @LinkedServer + ']';

SET @@sqlstate = '';
SET @@INVOICE_NO = @INVOICE_NO;
SET @@INVOICE_ID = @INVOICE_ID;

SET @@sqlstate = '
	SELECT NTABLE.*, EFAKTUR.TAX_INVOICE_DT_STR, EFAKTUR.TAX_AMOUNT FROM (
	SELECT DISTINCT TOP 1
	GR.PO_CATEGORY,
	INV.INVOICE_NO,
	INV.INVOICE_ID,
	INV.STATUS,
	INV.INVOICE_DATE,
	CONVERT(VARCHAR(30), INV.INVOICE_DATE , 104) as INVOICE_DATE_STR,
	INV.TURN_OVER,
	INV.TAX_BASE,
	INV.CALCULATE_TAX,
	INV.WITHOLDING_TAX_CD,
	INV.SUPPLIER_CD,
	INV.CHECKBOX_STAMP,
	INV.TOTAL_AMOUNT,
	INV.TAX_INVOICE_AMOUNT,
	INV.TAX_INVOICE_NO,
	INV.NOTICE_FLAG,
	INV.CERTIFICATE_ID,
	(SELECT COUNT(1) FROM TB_R_GR_IR_FROM_SAP WHERE INVOICE_ID = INV.INVOICE_ID) as TOTAL_GR_ITEM
	FROM TB_R_INVOICE INV
	JOIN TB_R_GR_IR_FROM_SAP GR
	ON GR.INVOICE_ID = INV.INVOICE_ID 
	WHERE 
	INV.INVOICE_NO = '''+@@INVOICE_NO+'''
	AND INV.INVOICE_ID = '+@@INVOICE_ID+' ) NTABLE
	LEFT JOIN (
	SELECT 
	INVOICE_NO,
	TAX_INVOICE_DT_STR,
	TAX_AMOUNT
	FROM OPENQUERY('+ @@LinkedServer + ', 
	''SELECT 
	INVOICE_NO AS INVOICE_NO,
	CONVERT(VARCHAR(30), VAT.TAX_INVOICE_DT , 104) AS TAX_INVOICE_DT_STR,
	VAT.VAT_PRICE AS TAX_AMOUNT
	FROM TMMIN_E_FAKTUR_UAT.dbo.TB_R_VAT_IN_H VAT 
	'')) EFAKTUR 
	ON NTABLE.INVOICE_NO = EFAKTUR.INVOICE_NO
';

execute(@@sqlstate);