exec GET_PROCUREMENT_TRACKING_EXCEL 
	@@RECEIVED_DATE_FROM = @RECEIVED_DATE_FROM, 
	@@RECEIVED_DATE_TO = @RECEIVED_DATE_TO,
	@@PLAN_PAYMENT_DATE_FROM = @PLAN_PAYMENT_DATE_FROM,
	@@PLAN_PAYMENT_DATE_TO = @PLAN_PAYMENT_DATE_TO, 
	@@TAX_INVOICE_NO = @TAX_INVOICE_NO, 
	@@SUPPLIER = @SUPPLIER, 
	@@VERIFY_STATUS = @VERIFY_STATUS, 
	@@INVOICE_NO = @INVOICE_NO, 
	@@AP_DOC_NO = @AP_DOC_NO, 
	@@PAYMENT_STATUS = @PAYMENT_STATUS, 
	@@ACTUAL_PAYMENT_DATE_FROM = @ACTUAL_PAYMENT_DATE_FROM, 
	@@ACTUAL_PAYMENT_DATE_TO = @ACTUAL_PAYMENT_DATE_TO,
	@@TRANS_TYPE = @TRANS_TYPE ;