
SELECT 
      s.SUPPLIER_CD
      ,SUPPLIER_NAME
	  ,LTRIM(RTRIM(PARTNER_BANK_CODE)) as PARTNER_BANK_CODE
	  ,LTRIM(RTRIM(PARTNER_BANK_TYPE)) as PARTNER_BANK_TYPE
	  ,LTRIM(RTRIM(CURRENCY)) as CURRENCY
	  ,LTRIM(RTRIM(PARTNER_BANK_NAME)) as PARTNER_BANK_NAME
  FROM TB_M_SUPPLIER s
  left join TB_M_SUPPLIER_PARTNER_BANK_DETAIL bank on s.SUPPLIER_CD = bank.SUPPLIER_CD
  where s.SUPPLIER_CD = @SUPPLIER_CD
  order by s.SUPPLIER_CD