SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION

DECLARE @@SUPPLIER_CD VARCHAR(10);
DECLARE @@CREATED_BY VARCHAR(10);
DECLARE @@SEQ_TYPE VARCHAR(100);
DECLARE @@SEQ AS INT

SET @@SUPPLIER_CD = @SUPPLIER_CD;
SET @@CREATED_BY = @CREATED_BY;
SET @@SEQ_TYPE = @SEQ_TYPE;

SELECT @@SEQ = SEQ_NUMBER FROM TB_M_SEQ_NUMBER WHERE SUPPLIER_CD = @@SUPPLIER_CD AND [YEAR] = YEAR(GETDATE());

IF @@SEQ IS NULL
	BEGIN
		SET @@SEQ = 1;
		INSERT INTO TB_M_SEQ_NUMBER (SEQ_TYPE, SEQ_NUMBER, SUPPLIER_CD, [YEAR], CREATED_DT, CREATED_BY)
		VALUES ( @@SEQ_TYPE, @@SEQ, @@SUPPLIER_CD, YEAR(GETDATE()), GETDATE(), @@CREATED_BY );
		SELECT @@SEQ;
	END	
ELSE
	BEGIN
		SET @@SEQ += 1;
		UPDATE TB_M_SEQ_NUMBER SET SEQ_NUMBER = @@SEQ WHERE SUPPLIER_CD = @@SUPPLIER_CD AND [YEAR] = YEAR(GETDATE());
		SELECT @@SEQ;
	END
COMMIT TRANSACTION