INSERT INTO TB_M_SYSTEM
(          
    SYSTEM_CD,
    SYSTEM_TYPE,
    SYSTEM_VALUE_TEXT,
	SYSTEM_VALUE_NUM,
	SYSTEM_VALUE_DT,
	SYSTEM_DESC,
    CREATED_BY,
	CREATED_DT 
) 
VALUES 
(
    @SYSTEM_CD,  
    @SYSTEM_TYPE,  
    @SYSTEM_VALUE_TEXT, 
	@SYSTEM_VALUE_NUM,
	@SYSTEM_VALUE_DT, 
	@SYSTEM_DESC,
	@CREATED_BY,    
    GETDATE()
);

