
DELETE TB_T_INVOICE_ATTACHMENT
WHERE INVOICE_ID = @INVOICE_ID

INSERT INTO [dbo].[TB_T_INVOICE_ATTACHMENT]
           ([ATTACHMENT_TYPE]
           ,[INVOICE_ID]
           ,[FILE_NAME]
           ,[FILE_NAME_SERVER]
           ,[CREATED_DT]
           ,[CREATED_BY])
SELECT 
ATTACHMENT_TYPE,
@INVOICE_ID,
[FILE_NAME],
FILE_NAME_SERVER,
getdate(),
@CREATED_BY
FROM TB_R_INVOICE_ATTACHMENT
WHERE INVOICE_ID = @INVOICE_ID

