INSERT INTO TB_M_ANNOUNCEMENT
(          
     [ANNOUNCEMENT_TITLE]
    ,[DATE_RELEASE]
    ,[FILE_LOCATION]
    ,[STATUS]
	,[CREATED_BY]
    ,[CREATED_DT]
) 
VALUES 
(
	@DOCUMENT_TITLE,
    @RELEASE_DATE,
    @FILE_LOCATION,
    @STATUS,
	@CREATED_BY,    
    GETDATE()
);