INSERT INTO TB_R_INVOICE
(          
    INVOICE_NO,
	INVOICE_DATE,
    TURN_OVER,
    TAX_BASE,
	CALCULATE_TAX,
	CHECKBOX_STAMP,
	STAMP_AMOUNT,
	TOTAL_AMOUNT,
	[STATUS],
	SUPPLIER_CD,
	CURRENCY,
	TAX_INVOICE_NO,
	CERTIFICATE_ID,
	TAX_INVOICE_AMOUNT,
    CREATED_BY,
	CREATED_DT,
	WITHOLDING_TAX_CD,
	TAX_CODE--add by fid.ahmad 04-10-2022
) 
 VALUES 
(
    @INVOICE_NO,
	@INVOICE_DATE,  
    @TURN_OVER,  
    @TAX_BASE,  
	@CALCULATE_TAX,
	@CHECKBOX_STAMP,
	@STAMP_AMOUNT,
	@TOTAL_AMOUNT,
	@STATUS,
	@SUPPLIER_CD,
	@CURRENCY,
	@TAX_INVOICE_NO,
	@CERTIFICATE_ID,
	@TAX_INVOICE_AMOUNT,
	@CREATED_BY,    
    GETDATE(),
	@WITHOLDING_TAX_CD,
	(SELECT ISNULL(SYSTEM_VALUE_TEXT,'') AS SYSTEM_VALUE_TEXT FROM TB_M_SYSTEM WHERE SYSTEM_TYPE='TAX_CODE_MAPP' AND SYSTEM_CD= CAST (REPLACE(@CALCULATE_TAX,'.0','') AS VARCHAR))
);

SELECT @@@@IDENTITY;
