
INSERT INTO [TB_R_PO_ITEM]
           ([PO_NUMBER]
           ,[PO_ITEM]
           ,[INVOICE_FLG]
           ,[PR_NUMBER]
           ,[PR_ITEM]
           ,[MAT_NUMBER]
           ,[MAT_DESCR]
           ,[VAL_CLASS]
           ,[DELIV_PLAN_DT]
           ,[PLANT_CODE]
           ,[SLOC_CODE]
           ,[WBS_NUMBER]
           ,[COST_CTR]
           ,[PO_QTY_ORI]
           ,[PO_QTY_NEW]
           ,[PO_QTY_USED]
           ,[PO_UNIT]
           ,[PRICE_PER_UNIT]
           ,[ITM_DEL_FLG]
           ,[TAX_CODE]
           ,[CREATED_DT]
           ,[CREATED_BY]
           )
     VALUES
           (@PO_NUMBER
           ,@PO_ITEM
           ,@INVOICE_FLG
           ,@PR_NUMBER
           ,@PR_ITEM
           ,@MAT_NUMBER
           ,@MAT_DESCR
           ,@VAL_CLASS
           ,@DELIV_PLAN_DT
           ,@PLANT_CODE
           ,@SLOC_CODE
           ,@WBS_NUMBER
           ,@COST_CTR
           ,@PO_QTY_ORI
           ,@PO_QTY_NEW
           ,@PO_QTY_USED
           ,@PO_UNIT
           ,@PRICE_PER_UNIT
           ,@ITM_DEL_FLG
           ,@TAX_CODE
           ,getdate()
           ,@CREATED_BY
          );
