DECLARE @@PARAM VARCHAR(MAX)
	,@@StartData INT
	,@@EndData INT

SET @@PARAM = @PARAM
SET @@StartData = @StartData
SET @@EndData = @EndData

SELECT A.*
FROM (
	SELECT ROW_NUMBER() OVER (
			ORDER BY PLANT_CD ASC
				,PLANT_NAME
			) AS ROWNO
		,PLANT_CD
		,PLANT_NAME
		,CREATED_BY
		,CONVERT(VARCHAR, CREATED_DT, 121) AS CREATED_DT
		,CHANGED_BY
		,CONVERT(VARCHAR, CHANGED_DT, 121) AS CHANGED_DT
	FROM TB_M_PLANT
	WHERE 1 = 1
		AND (
			PLANT_CD LIKE '%' + @@PARAM + '%'
			OR PLANT_NAME LIKE '%' + @@PARAM + '%'
			)
	) A
WHERE A.ROWNO BETWEEN @@StartData
		AND @@EndData