DECLARE @@SUPP_AUTO_POSTING VARCHAR(1), @@WHT VARCHAR(4), @@WHTV VARCHAR(4)


SELECT @@SUPP_AUTO_POSTING = B.AUTO_POSTING_FLAG 
FROM TB_R_INVOICE A
	JOIN TB_M_SUPPLIER B ON A.SUPPLIER_CD = B.SUPPLIER_CD
WHERE A.CERTIFICATE_ID = @CERTIFICATE_ID

SELECT TOP 1 @@WHT = C.WITHOLDING_TAX_CD
FROM TB_R_INVOICE C
	JOIN TB_M_SUPPLIER D ON C.SUPPLIER_CD = D.SUPPLIER_CD
WHERE C.CERTIFICATE_ID = @CERTIFICATE_ID

SELECT TOP 1 @@WHTV = E.WITHOLDING_CODE
FROM TB_R_INVOICE F
	JOIN TB_M_SUPPLIER E ON E.SUPPLIER_CD = F.SUPPLIER_CD
WHERE F.CERTIFICATE_ID = @CERTIFICATE_ID

IF @RECEIVED_STATUS = 'ACCEPT'
BEGIN 
	IF (ISNULL(@@SUPP_AUTO_POSTING,'')!='' AND @@SUPP_AUTO_POSTING = 'Y')
	BEGIN
		UPDATE 
			TB_R_INVOICE
		SET 
			RECEIVED_STATUS = @RECEIVED_STATUS		
			,RECEIVED_DT =  getdate()
			--,PAYMENT_PLAN_DATE = (SELECT TOP 1 WORKING_DATE     
			--					  FROM TB_M_WORKING_CALENDAR
			--					  where WORKING_DATE >= @PAYMENT_PLAN_DATE
			--					  and WORKING_FLAG = '1'
			--					  order by WORKING_DATE asc)
			--,[STATUS] = 'READY_TO_POST'
			,HARDCOPY_STATUS = 'ACCEPT'
			--,SUBMIT_DT = getdate()
			--,SUBMIT_BY = @UPDATED_BY
			,UPDATED_DT = getdate()
			,UPDATED_BY = @UPDATED_BY
		WHERE
			1 = 1
			and CERTIFICATE_ID = @CERTIFICATE_ID
	END
	ELSE
	BEGIN
		IF(ISNULL(@@WHT, '') = ISNULL(@@WHTV, ''))
		BEGIN
			UPDATE 
				TB_R_INVOICE
			SET 
				RECEIVED_STATUS = @RECEIVED_STATUS		
				,RECEIVED_DT =  getdate()
				--,PAYMENT_PLAN_DATE = (SELECT TOP 1 WORKING_DATE     
				--					  FROM TB_M_WORKING_CALENDAR
				--					  where WORKING_DATE >= @PAYMENT_PLAN_DATE
				--					  and WORKING_FLAG = '1'
				--					  order by WORKING_DATE asc)
				--,[STATUS] = 'READY_TO_POST'
				,HARDCOPY_STATUS = 'ACCEPT'
				--,SUBMIT_DT = getdate()
				--,SUBMIT_BY = @UPDATED_BY
				,UPDATED_DT = getdate()
				,UPDATED_BY = @UPDATED_BY
			WHERE
				1 = 1
				and CERTIFICATE_ID = @CERTIFICATE_ID
		END
		ELSE
		BEGIN
			UPDATE 
				TB_R_INVOICE
			SET 
				RECEIVED_STATUS = @RECEIVED_STATUS		
				,RECEIVED_DT =  getdate()
				--,PAYMENT_PLAN_DATE = (SELECT TOP 1 WORKING_DATE     
				--					  FROM TB_M_WORKING_CALENDAR
				--					  where WORKING_DATE >= @PAYMENT_PLAN_DATE
				--					  and WORKING_FLAG = '1'
				--					  order by WORKING_DATE asc)
				--,[STATUS] = 'SUBMITTED'
				,HARDCOPY_STATUS = 'ACCEPT'
				--,SUBMIT_DT = getdate()
				--,SUBMIT_BY = @UPDATED_BY
				,UPDATED_DT = getdate()
				,UPDATED_BY = @UPDATED_BY
			WHERE
				1 = 1
				and CERTIFICATE_ID = @CERTIFICATE_ID
		END
	END
END

IF @RECEIVED_STATUS = 'REJECT'
BEGIN 
	UPDATE 
		TB_R_INVOICE
	SET 
		RECEIVED_STATUS = @RECEIVED_STATUS
		,RECEIVED_DT =  getdate()
		--,[STATUS] = 'REJECTED'
		,HARDCOPY_STATUS = 'REJECT'
		--,NOTICE_DATE = CAST(CONVERT(datetime,  @NOTICE_DATE , 104) as DATE)
		--,NOTICE_REMARK = @NOTICE_REMARK
		--,NOTICE_BY = @NOTICE_BY
		,UPDATED_DT = getdate()
		,UPDATED_BY = @UPDATED_BY
	WHERE 
		1 = 1
		and CERTIFICATE_ID = @CERTIFICATE_ID
END