update 
	TB_R_INVOICE
set 
	[STATUS] = @NEW_STATUS,	
	INVOICE_NOTE = @INVOICE_NOTE,
	TAX_CODE = @TAX_CODE,
	ASSIGNMENT = @ASSIGNMENT,
	BASELINE_DT = @BASELINE_DT,
	TERM_PAY = @TERM_PAY,
	PAY_METHOD = @PAY_METHOD,
	LOG_DOC_NO = @LOG_DOC_NO,
	SAP_DOC_NO = @SAP_DOC_NO,
	POSTED_BY = @POSTED_BY,
	POSTED_DT = @POSTED_DT,
	SAP_YEAR = @SAP_YEAR,
	UPDATED_BY = @UPDATED_BY,
	UPDATED_DT = getdate()
where 
	1=1
and INVOICE_ID = @INVOICE_ID



update 
	TB_R_GR_IR_FROM_SAP
set
	GR_STATUS = @NEW_STATUS,
	UPDATED_BY = @UPDATED_BY,
	UPDATED_DT = getdate()
where 
	1=1
and INVOICE_ID = @INVOICE_ID