select * from
(
select SYSTEM_VALUE_TEXT,SYSTEM_VALUE_NUM from TB_M_SYSTEM
where SYSTEM_ID = 'TMMIN' and SYSTEM_TYPE = 'NAME'

union

select SYSTEM_VALUE_TEXT,SYSTEM_VALUE_NUM from TB_M_SYSTEM
where SYSTEM_ID = 'TMMIN' and SYSTEM_TYPE = 'ADDRESS'
	
union
	
select SYSTEM_VALUE_TEXT,SYSTEM_VALUE_NUM from TB_M_SYSTEM
where SYSTEM_ID = 'TMMIN' and SYSTEM_TYPE = 'NPWP' 
)as TB
order by TB.SYSTEM_VALUE_NUM