DECLARE @@PLANT_CD VARCHAR(MAX)
	,@@SLOC_CD VARCHAR(MAX)
	,@@PIC VARCHAR(MAX)
	,@@StartData INT
	,@@EndData INT

SET @@PLANT_CD = @PLANT_CD
SET @@SLOC_CD = @SLOC_CD
SET @@PIC = @PIC
SET @@StartData = @StartData
SET @@EndData = @EndData

SELECT A.*
FROM (
	SELECT ROW_NUMBER() OVER (
			ORDER BY PLANT_CD ASC
				,SLOC_CD ASC
				,PIC ASC
			) AS ROWNO
		,PLANT_CD
		,SLOC_CD
		,PIC
		,DELETION_FLAG
		,CREATED_BY
		,CONVERT(VARCHAR, CREATED_DT, 121) AS CREATED_DT
		,CHANGED_BY
		,CONVERT(VARCHAR, CHANGED_DT, 121) AS CHANGED_DT
	FROM TB_M_UNIT_APPROVER
	WHERE 1 = 1
		AND (
			PLANT_CD = @@PLANT_CD
			OR @@PLANT_CD = ''
			)
		AND (
			SLOC_CD = @@SLOC_CD
			OR @@SLOC_CD = ''
			)
		AND (
			PIC = @@PIC
			OR @@PIC = ''
			)
	) A
WHERE A.ROWNO BETWEEN @@StartData
		AND @@EndData