DECLARE @@PLANT_CD VARCHAR(MAX)
	,@@SLOC_CD VARCHAR(MAX)
	,@@PIC VARCHAR(MAX)

SET @@PLANT_CD = @PLANT_CD
SET @@SLOC_CD = @SLOC_CD
SET @@PIC = @PIC

SELECT COUNT(*)
FROM TB_M_UNIT_APPROVER
WHERE 1 = 1
	AND (
		PLANT_CD = @@PLANT_CD
		OR @@PLANT_CD = ''
		)
	AND (
		SLOC_CD = @@SLOC_CD
		OR @@SLOC_CD = ''
		)
	AND (
		PIC = @@PIC
		OR @@PIC = ''
		)