UPDATE 
	TB_R_RF_REGISTER
SET 
	[RF_NO] = @RF_NO
	,[RF_DT] = @RF_DT
	,[PIC_USER] = @PIC_USER
	,[DIVISION] = @DIVISION
	,[WBS_NO] = @WBS_NO
	,[TOTAL_AMOUNT] = @TOTAL_AMOUNT
	,[UPDATED_BY] = @CHANGED_BY
	,[UPDATED_DT] = getdate()
WHERE 
	1 = 1
	and RF_REGISTER_ID = @RF_REGISTER_ID

