update 
	TB_R_INVOICE
set 
	REVERSE_REASON = @REASON_IN,
	REVERSE_POST_DT = @POST_DATE_IN,
	ON_PROCESS_SAP_REV = 'Y',
	UPDATED_BY = @UPDATED_BY,
	UPDATED_DT = getdate()
where 
	1=1
and INVOICE_ID = @INVOICE_ID

