UPDATE 
	TB_M_SUPPLIER
SET 
	PKP_FLAG = @PKP_FLAG
	,EDIT_AMOUNT_FLAG = @EDIT_AMOUNT_FLAG
	,PPN_RATE = @PPN_RATE
	,EMAIL = @EMAIL
	,AUTO_POSTING_FLAG = @AUTO_POSTING_FLAG
	,WITHOLDING_CODE = @WITHOLDING_CODE
	,UPDATED_BY = @CHANGED_BY
	,UPDATED_DT = getdate()
	,SKB_FLAG = @SKB_FLAG
	,PLAT_KUNING_FLAG = @PLAT_KUNING_FLAG
	,SKB_VALID_FROM = (CASE WHEN @SKB_FLAG = 'N' THEN NULL
	ELSE @SKB_VALID_FROM--CONVERT(DATE, @SKB_VALID_FROM, 103)
	END)
	,SKB_VALID_TO = (CASE WHEN @SKB_FLAG = 'N' THEN NULL
	ELSE @SKB_VALID_TO--CONVERT(DATE, @SKB_VALID_TO, 103)
	END)
WHERE 
	1 = 1
	and SUPPLIER_ID = @SUPPLIER_ID

