UPDATE 
	TB_M_USER_SAP
SET 
    USERNAME = @USERNAME
	,COMPLETE_NAME = @COMPLETE_NAME
	,[GROUP] = @GROUP
	,NOREG = @NOREG
	,UPDATED_BY = @UPDATED_BY
	,UPDATED_DT = getdate()
WHERE 
	1 = 1
	and [USER_ID] = @USER_ID

