UPDATE 
	TB_M_MAINTENANCE_APPROVAL
SET 
    SUPPLIER_CD = @SUPPLIER_CD
	,APPROVER_UNIT_CD = @APPROVER_UNIT_CD
	,UPDATED_BY = @UPDATED_BY
	,UPDATED_DT = getdate()
WHERE 
	1 = 1
	and MAINTENANCE_APPROVAL_ID = @MAINTENANCE_APPROVAL_ID

