UPDATE 
	TB_M_GL_ACCOUNT
SET 
    [GL_ACCOUNT_NO] = @GL_ACCOUNT_NO
	,[CATEGORY_CD] = @CATEGORY_CD
	,[TYPE] = @TYPE
	,[NAME] = @NAME
	,[CODE] = @CODE
	,[PERCENTAGE] = @PERCENTAGE
	,[UPDATED_BY] = @CHANGED_BY
	,[UPDATED_DT] = getdate()
WHERE 
	1 = 1
	and GL_ACCOUNT_ID = @GL_ACCOUNT_ID

