SELECT 
	COUNT(*) 
FROM 
	TB_R_VAT_IN_H 
WHERE 
	TRANS_TYPE_CODE + '' + REPLACEMENT_FG + '' + TAX_INVOICE_NO = @TAX_INVOICE_NO 
	AND REPLACEMENT_FG = @REPLACEMENT_FG 
	--AND (MANUAL_ENTRY != 'Y' OR MANUAL_ENTRY IS NULL)